# Pakiet pandas

**Zadanie 1**
Rozważmy ramkę danych:
```python
import seaborn as sns
flights = sns.load_dataset('flights')
```
Zastosuj wektor etykiet hierarchicznych do nazwania wierszy ramki danych `flights`. Wykorzystaj do tego celu dane zawarte w kolumnach `year` i `month`.

In [ ]:
import seaborn as sns
flights = sns.load_dataset('flights')

In [ ]:
flights.set_index(['year', 'month'], inplace=True)
pd.set_option('display.max_rows', None)
flights

            passengers
year month
1949 Jan           112
     Feb           118
     Mar           132
     Apr           129
     May           121
     Jun           135
     Jul           148
     Aug           148
     Sep           136
     Oct           119
     Nov           104
     Dec           118
1950 Jan           115
     Feb           126
     Mar           141
     Apr           135
     May           125
     Jun           149
     Jul           170
     Aug           170
     Sep           158
     Oct           133
     Nov           114
     Dec           140
1951 Jan           145
     Feb           150
     Mar           178
     Apr           163
     May           172
     Jun           178
     Jul           199
     Aug           199
     Sep           184
     Oct           162
     Nov           146
     Dec           166
1952 Jan           171
     Feb           180
     Mar           193
     Apr           181
     May           183
     Jun           218
     Jul           230
     Aug           242
     Sep           209
     Oct           191
     Nov           172
     Dec           194
1953 Jan           196
     Feb           196
     Mar           236
     Apr           235
     May           229
     Jun           243
     Jul           264
     Aug           272
     Sep           237
     Oct           211
     Nov           180
     Dec           201
1954 Jan           204
     Feb           188
     Mar           235
     Apr           227
     May           234
     Jun           264
     Jul           302
     Aug           293
     Sep           259
     Oct           229
     Nov           203
     Dec           229
1955 Jan           242
     Feb           233
     Mar           267
     Apr           269
     May           270
     Jun           315
     Jul           364
     Aug           347
     Sep           312
     Oct           274
     Nov           237
     Dec           278
1956 Jan           284
     Feb           277
     Mar           317
     Apr           313
     May           318
     Jun           374
     Jul           413
     Aug           405
     Sep           355
     Oct           306
     Nov           271
     Dec           306
1957 Jan           315
     Feb           301
     Mar           356
     Apr           348
     May           355
     Jun           422
     Jul           465
     Aug           467
     Sep           404
     Oct           347
     Nov           305
     Dec           336
1958 Jan           340
     Feb           318
     Mar           362
     Apr           348
     May           363
     Jun           435
     Jul           491
     Aug           505
     Sep           404
     Oct           359
     Nov           310
     Dec           337
1959 Jan           360
     Feb           342
     Mar           406
     Apr           396
     May           420
     Jun           472
     Jul           548
     Aug           559
     Sep           463
     Oct           407
     Nov           362
     Dec           405
1960 Jan           417
     Feb           391
     Mar           419
     Apr           461
     May           472
     Jun           535
     Jul           622
     Aug           606
     Sep           508
     Oct           461
     Nov           390
     Dec           432

**Zadanie 2**
Podziel ramkę danych `iris` na dwie rozłączne części (ramki): niech pierwsza zawiara $80\%$ obserwacji, a druga — pozostałe $20\%$.
```python
import seaborn as sns
iris = sns.load_dataset('iris')
```

In [ ]:
iris = sns.load_dataset('iris')

In [ ]:
iris_shuffled = iris.sample(frac=1, random_state=42).reset_index(drop=True)

split_index = int(len(iris_shuffled) * 0.8)
df1 = iris_shuffled.iloc[:split_index]
df2 = iris_shuffled.iloc[split_index:]

print(f'Rozmiar df1: {df1.shape}')
print(f'Rozmiar df2: {df2.shape}')

Rozmiar df1: (120, 5)
Rozmiar df2: (30, 5)

**Zadanie 3**
Dokonaj standaryzacji wszystkich zmiennych liczbowych w ramce danych `iris`.

In [ ]:
numeric_cols = iris.select_dtypes(include='number').columns

iris[numeric_cols] = (iris[numeric_cols] - iris[numeric_cols].mean()) / iris[numeric_cols].std()

iris

     sepal_length  sepal_width  petal_length  petal_width     species
0       -0.897674     1.015602     -1.335752    -1.311052      setosa
1       -1.139200    -0.131539     -1.335752    -1.311052      setosa
2       -1.380727     0.327318     -1.392399    -1.311052      setosa
3       -1.501490     0.097889     -1.279104    -1.311052      setosa
4       -1.018437     1.245030     -1.335752    -1.311052      setosa
5       -0.535384     1.933315     -1.165809    -1.048667      setosa
6       -1.501490     0.786174     -1.335752    -1.179859      setosa
7       -1.018437     0.786174     -1.279104    -1.311052      setosa
8       -1.743017    -0.360967     -1.335752    -1.311052      setosa
9       -1.139200     0.097889     -1.279104    -1.442245      setosa
10      -0.535384     1.474458     -1.279104    -1.311052      setosa
11      -1.259964     0.786174     -1.222456    -1.311052      setosa
12      -1.259964    -0.131539     -1.335752    -1.442245      setosa
13      -1.863780    -0.131539     -1.505695    -1.442245      setosa
14      -0.052331     2.162743     -1.449047    -1.311052      setosa
15      -0.173094     3.080455     -1.279104    -1.048667      setosa
16      -0.535384     1.933315     -1.392399    -1.048667      setosa
17      -0.897674     1.015602     -1.335752    -1.179859      setosa
18      -0.173094     1.703886     -1.165809    -1.179859      setosa
19      -0.897674     1.703886     -1.279104    -1.179859      setosa
20      -0.535384     0.786174     -1.165809    -1.311052      setosa
21      -0.897674     1.474458     -1.279104    -1.048667      setosa
22      -1.501490     1.245030     -1.562342    -1.311052      setosa
23      -0.897674     0.556746     -1.165809    -0.917474      setosa
24      -1.259964     0.786174     -1.052513    -1.311052      setosa
25      -1.018437    -0.131539     -1.222456    -1.311052      setosa
26      -1.018437     0.786174     -1.222456    -1.048667      setosa
27      -0.776911     1.015602     -1.279104    -1.311052      setosa
28      -0.776911     0.786174     -1.335752    -1.311052      setosa
29      -1.380727     0.327318     -1.222456    -1.311052      setosa
30      -1.259964     0.097889     -1.222456    -1.311052      setosa
31      -0.535384     0.786174     -1.279104    -1.048667      setosa
32      -0.776911     2.392171     -1.279104    -1.442245      setosa
33      -0.414621     2.621599     -1.335752    -1.311052      setosa
34      -1.139200     0.097889     -1.279104    -1.311052      setosa
35      -1.018437     0.327318     -1.449047    -1.311052      setosa
36      -0.414621     1.015602     -1.392399    -1.311052      setosa
37      -1.139200     1.245030     -1.335752    -1.442245      setosa
38      -1.743017    -0.131539     -1.392399    -1.311052      setosa
39      -0.897674     0.786174     -1.279104    -1.311052      setosa
40      -1.018437     1.015602     -1.392399    -1.179859      setosa
41      -1.622254    -1.737536     -1.392399    -1.179859      setosa
42      -1.743017     0.327318     -1.392399    -1.311052      setosa
43      -1.018437     1.015602     -1.222456    -0.786281      setosa
44      -0.897674     1.703886     -1.052513    -1.048667      setosa
45      -1.259964    -0.131539     -1.335752    -1.179859      setosa
46      -0.897674     1.703886     -1.222456    -1.311052      setosa
47      -1.501490     0.327318     -1.335752    -1.311052      setosa
48      -0.656147     1.474458     -1.279104    -1.311052      setosa
49      -1.018437     0.556746     -1.335752    -1.311052      setosa
50       1.396829     0.327318      0.533621     0.263260  versicolor
51       0.672249     0.327318      0.420326     0.394453  versicolor
52       1.276066     0.097889      0.646916     0.394453  versicolor
53      -0.414621    -1.737536      0.137087     0.132067  versicolor
54       0.793012    -0.590395      0.476973     0.394453  versicolor
55      -0.173094    -0.590395      0.420326     0.132067  versicolor
56       0.551486     0.556746      0.533621     0.525645  versicolor
57      -1.139200    -1.508108     -0.259446    -0.261511  versicolor
58       0.913776    -0.360967      0.476973     0.132067  versicolor
59      -0.776911    -0.819823      0.080440     0.263260  versicolor
60      -1.018437    -2.425820     -0.146151    -0.261511  versicolor
61       0.068433    -0.131539      0.250383     0.394453  versicolor
62       0.189196    -1.966964      0.137087    -0.261511  versicolor
63       0.309959    -0.360967      0.533621     0.263260  versicolor
64      -0.293857    -0.360967     -0.089503     0.132067  versicolor
65       1.034539     0.097889      0.363678     0.263260  versicolor
66      -0.293857    -0.131539      0.420326     0.394453  versicolor
67      -0.052331    -0.819823      0.193735    -0.261511  versicolor
68       0.430722    -1.966964      0.420326     0.394453  versicolor
69      -0.293857    -1.278680      0.080440    -0.130318  versicolor
70       0.068433     0.327318      0.590269     0.788031  versicolor
71       0.309959    -0.590395      0.137087     0.132067  versicolor
72       0.551486    -1.278680      0.646916     0.394453  versicolor
73       0.309959    -0.590395      0.533621     0.000875  versicolor
74       0.672249    -0.360967      0.307030     0.132067  versicolor
75       0.913776    -0.131539      0.363678     0.263260  versicolor
76       1.155302    -0.590395      0.590269     0.263260  versicolor
77       1.034539    -0.131539      0.703564     0.656838  versicolor
78       0.189196    -0.360967      0.420326     0.394453  versicolor
79      -0.173094    -1.049251     -0.146151    -0.261511  versicolor
80      -0.414621    -1.508108      0.023792    -0.130318  versicolor
81      -0.414621    -1.508108     -0.032856    -0.261511  versicolor
82      -0.052331    -0.819823      0.080440     0.000875  versicolor
83       0.189196    -0.819823      0.760211     0.525645  versicolor
84      -0.535384    -0.131539      0.420326     0.394453  versicolor
85       0.189196     0.786174      0.420326     0.525645  versicolor
86       1.034539     0.097889      0.533621     0.394453  versicolor
87       0.551486    -1.737536      0.363678     0.132067  versicolor
88      -0.293857    -0.131539      0.193735     0.132067  versicolor
89      -0.414621    -1.278680      0.137087     0.132067  versicolor
90      -0.414621    -1.049251      0.363678     0.000875  versicolor
91       0.309959    -0.131539      0.476973     0.263260  versicolor
92      -0.052331    -1.049251      0.137087     0.000875  versicolor
93      -1.018437    -1.737536     -0.259446    -0.261511  versicolor
94      -0.293857    -0.819823      0.250383     0.132067  versicolor
95      -0.173094    -0.131539      0.250383     0.000875  versicolor
96      -0.173094    -0.360967      0.250383     0.132067  versicolor
97       0.430722    -0.360967      0.307030     0.132067  versicolor
98      -0.897674    -1.278680     -0.429389    -0.130318  versicolor
99      -0.173094    -0.590395      0.193735     0.132067  versicolor
100      0.551486     0.556746      1.270040     1.706379   virginica
101     -0.052331    -0.819823      0.760211     0.919223   virginica
102      1.517592    -0.131539      1.213393     1.181609   virginica
103      0.551486    -0.360967      1.043450     0.788031   virginica
104      0.793012    -0.131539      1.156745     1.312801   virginica
105      2.121409    -0.131539      1.609926     1.181609   virginica
106     -1.139200    -1.278680      0.420326     0.656838   virginica
107      1.759119    -0.360967      1.439983     0.788031   virginica
108      1.034539    -1.278680      1.156745     0.788031   virginica
109      1.638355     1.245030      1.326688     1.706379   virginica
110      0.793012     0.327318      0.760211     1.050416   virginica
111      0.672249    -0.819823      0.873507     0.919223   virginica
112      1.155302    -0.131539      0.986802     1.181609   virginica
113     -0.173094    -1.278680      0.703564     1.050416   virginica
114     -0.052331    -0.590395      0.760211     1.575187   virginica
115      0.672249     0.327318      0.873507     1.443994   virginica
116      0.793012    -0.131539      0.986802     0.788031   virginica
117      2.242172     1.703886      1.666574     1.312801   virginica
118      2.242172    -1.049251      1.779869     1.443994   virginica
119      0.189196    -1.966964      0.703564     0.394453   virginica
120      1.276066     0.327318      1.100097     1.443994   virginica
121     -0.293857    -0.590395      0.646916     1.050416   virginica
122      2.242172    -0.590395      1.666574     1.050416   virginica
123      0.551486    -0.819823      0.646916     0.788031   virginica
124      1.034539     0.556746      1.100097     1.181609   virginica
125      1.638355     0.327318      1.270040     0.788031   virginica
126      0.430722    -0.590395      0.590269     0.788031   virginica
127      0.309959    -0.131539      0.646916     0.788031   virginica
128      0.672249    -0.590395      1.043450     1.181609   virginica
129      1.638355    -0.131539      1.156745     0.525645   virginica
130      1.879882    -0.590395      1.326688     0.919223   virginica
131      2.483699     1.703886      1.496631     1.050416   virginica
132      0.672249    -0.590395      1.043450     1.312801   virginica
133      0.551486    -0.590395      0.760211     0.394453   virginica
134      0.309959    -1.049251      1.043450     0.263260   virginica
135      2.242172    -0.131539      1.326688     1.443994   virginica
136      0.551486     0.786174      1.043450     1.575187   virginica
137      0.672249     0.097889      0.986802     0.788031   virginica
138      0.189196    -0.131539      0.590269     0.788031   virginica
139      1.276066     0.097889      0.930154     1.181609   virginica
140      1.034539     0.097889      1.043450     1.575187   virginica
141      1.276066     0.097889      0.760211     1.443994   virginica
142     -0.052331    -0.819823      0.760211     0.919223   virginica
143      1.155302     0.327318      1.213393     1.443994   virginica
144      1.034539     0.556746      1.100097     1.706379   virginica
145      1.034539    -0.131539      0.816859     1.443994   virginica
146      0.551486    -1.278680      0.703564     0.919223   virginica
147      0.793012    -0.131539      0.816859     1.050416   virginica
148      0.430722     0.786174      0.930154     1.443994   virginica
149      0.068433    -0.131539      0.760211     0.788031   virginica

**Zadanie 4**
1. Utwórz zmienną (`Series`) reprezentująca małe litery alfabetu łacińskiego.
2. Utwórz zmienną (`Series`) zawierającą wszystkie kombinacje wielkich liter i cyfr.

In [ ]:
import string
import itertools

lowercase_series = pd.Series(list(string.ascii_lowercase))
uppercase_digits = pd.Series([''.join(x) for x in itertools.product(string.ascii_uppercase, string.digits)])

print("Małe litery alfabetu łacińskiego:")
print(lowercase_series)

print("\nKombinacje wielkich liter i cyfr:")
print(uppercase_digits)

Małe litery alfabetu łacińskiego:
0     a
1     b
2     c
3     d
4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

Kombinacje wielkich liter i cyfr:
0      A0
1      A1
2      A2
3      A3
4      A4
5      A5
6      A6
7      A7
8      A8
9      A9
10     B0
11     B1
12     B2
13     B3
14     B4
15     B5
16     B6
17     B7
18     B8
19     B9
20     C0
21     C1
22     C2
23     C3
24     C4
25     C5
26     C6
27     C7
28     C8
29     C9
30     D0
31     D1
32     D2
33     D3
34     D4
35     D5
36     D6
37     D7
38     D8
39     D9
40     E0
41     E1
42     E2
43     E3
44     E4
45     E5
46     E6
47     E7
48     E8
49     E9
50     F0
51     F1
52     F2
53     F3
54     F4
55     F5
56     F6
57     F7
58     F8
59     F9
60     G0
61     G1
62     G2
63     G3
64     G4
65     G5
66     G6
67     G7
68     G8
69     G9
70     H0
71     H1
72     H2
73     H3
74     H4
75     H5
76     H6
77     H7
78     H8
79     H9
80     I0
81     I1
82     I2
83     I3
84     I4
85     I5
86     I6
87     I7
88     I8
89     I9
90     J0
91     J1
92     J2
93     J3
94     J4
95     J5
96     J6
97     J7
98     J8
99     J9
100    K0
101    K1
102    K2
103    K3
104    K4
105    K5
106    K6
107    K7
108    K8
109    K9
110    L0
111    L1
112    L2
113    L3
114    L4
115    L5
116    L6
117    L7
118    L8
119    L9
120    M0
121    M1
122    M2
123    M3
124    M4
125    M5
126    M6
127    M7
128    M8
129    M9
130    N0
131    N1
132    N2
133    N3
134    N4
135    N5
136    N6
137    N7
138    N8
139    N9
140    O0
141    O1
142    O2
143    O3
144    O4
145    O5
146    O6
147    O7
148    O8
149    O9
150    P0
151    P1
152    P2
153    P3
154    P4
155    P5
156    P6
157    P7
158    P8
159    P9
160    Q0
161    Q1
162    Q2
163    Q3
164    Q4
165    Q5
166    Q6
167    Q7
168    Q8
169    Q9
170    R0
171    R1
172    R2
173    R3
174    R4
175    R5
176    R6
177    R7
178    R8
179    R9
180    S0
181    S1
182    S2
183    S3
184    S4
185    S5
186    S6
187    S7
188    S8
189    S9
190    T0
191    T1
192    T2
193    T3
194    T4
195    T5
196    T6
197    T7
198    T8
199    T9
200    U0
201    U1
202    U2
203    U3
204    U4
205    U5
206    U6
207    U7
208    U8
209    U9
210    V0
211    V1
212    V2
213    V3
214    V4
215    V5
216    V6
217    V7
218    V8
219    V9
220    W0
221    W1
222    W2
223    W3
224    W4
225    W5
226    W6
227    W7
228    W8
229    W9
230    X0
231    X1
232    X2
233    X3
234    X4
235    X5
236    X6
237    X7
238    X8
239    X9
240    Y0
241    Y1
242    Y2
243    Y3
244    Y4
245    Y5
246    Y6
247    Y7
248    Y8
249    Y9
250    Z0
251    Z1
252    Z2
253    Z3
254    Z4
255    Z5
256    Z6
257    Z7
258    Z8
259    Z9
dtype: object

**Zadanie 5**
Rozważmy remkę:
```python
import seaborn as sns
tips = sns.load_dataset('tips')
```
Utwórz tablicę kontyngencji dla kombinacji zmiennych `tips.smoker`, `tips.sex` oraz `tips.day`.

In [ ]:
tips = sns.load_dataset('tips')
contingency_table = pd.crosstab(index=[tips['smoker'], tips['sex']], columns=tips['day'])

contingency_table

day            Thur  Fri  Sat  Sun
smoker sex
Yes    Male      10    8   27   15
       Female     7    7   15    4
No     Male      20    2   32   43
       Female    25    2   13   14

**Zadanie 6**

Oblicz, jaką część rachunku stanowi napiwek, i podaj podsumowania liczbowe tych wartości (także w podgrupach utworzonych na podstawie zmiennych jakościowych dostępnych w ramce danych `tips`).

In [ ]:
tips['tip_ratio'] = tips['tip'] / tips['total_bill']

summary = tips.groupby(['day', 'sex', 'smoker'])['tip_ratio'].describe()

summary

<ipython-input-32-f4b2158e957a>:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  summary = tips.groupby(['day', 'sex', 'smoker'])['tip_ratio'].describe()

                    count      mean       std       min       25%       50%  \
day  sex    smoker
Thur Male   Yes      10.0  0.164417  0.045764  0.090014  0.134878  0.153660
            No       20.0  0.165706  0.047097  0.078616  0.130616  0.165223
     Female Yes       7.0  0.163073  0.031535  0.115982  0.153143  0.153846
            No       25.0  0.155971  0.030925  0.072961  0.139615  0.146886
Fri  Male   Yes       8.0  0.144730  0.039855  0.103555  0.117746  0.133739
            No        2.0  0.138005  0.024918  0.120385  0.129195  0.138005
     Female Yes       7.0  0.209129  0.041294  0.153657  0.184486  0.198216
            No        2.0  0.165296  0.031733  0.142857  0.154077  0.165296
Sat  Male   Yes      27.0  0.139067  0.051455  0.035638  0.085932  0.144823
            No       32.0  0.162132  0.040635  0.098204  0.136428  0.154352
     Female Yes      15.0  0.163817  0.075450  0.056433  0.109712  0.155219
            No       13.0  0.147993  0.037135  0.056797  0.135535  0.149355
Sun  Male   Yes      15.0  0.173964  0.162937  0.065660  0.095066  0.106205
            No       43.0  0.158291  0.041498  0.071804  0.133341  0.162778
     Female Yes       4.0  0.237075  0.120247  0.167464  0.170364  0.182084
            No       14.0  0.165710  0.046007  0.059447  0.147451  0.158623

                         75%       max
day  sex    smoker
Thur Male   Yes     0.194484  0.241255
            No      0.195903  0.266312
     Female Yes     0.176942  0.211509
            No      0.179641  0.208967
Fri  Male   Yes     0.155201  0.223776
            No      0.146815  0.155625
     Female Yes     0.239789  0.263480
            No      0.176515  0.187735
Sat  Male   Yes     0.188626  0.205577
            No      0.187737  0.291990
     Female Yes     0.193090  0.325733
            No      0.175747  0.199203
Sun  Male   Yes     0.205486  0.710345
            No      0.182930  0.241663
     Female Yes     0.248795  0.416667
            No      0.200377  0.252672

**Zadanie 7**

Wyznacz podstawowe statystyki próbkowe (średnia, odchylenie standardowe, kwantyle) dla liczby pasażerów (`flights`) w każdym roku z osobna. Przedstaw wyniki w tak sposób, by zagregowane wartości przechowywane były w kolumnach, a kolejne lata - w wierszach.

In [ ]:
import pandas as pd

stats = flights.groupby('year')['passengers'].agg(
    mean='mean',
    std='std',
    q25=lambda x: x.quantile(0.25),
    median=lambda x: x.median(),
    q75=lambda x: x.quantile(0.75)
).reset_index()

stats.set_index('year', inplace = True)

print(stats)

            mean        std     q25  median     q75
year
1949  126.666667  13.720147  118.00   125.0  135.25
1950  139.666667  19.070841  125.75   137.5  151.25
1951  170.166667  18.438267  159.00   169.0  179.50
1952  197.000000  22.966379  180.75   192.0  211.25
1953  225.000000  28.466887  199.75   232.0  238.50
1954  238.916667  34.924486  221.25   231.5  260.25
1955  284.000000  42.140458  260.75   272.0  312.75
1956  328.250000  47.861780  300.50   315.0  359.75
1957  368.416667  57.890898  330.75   351.5  408.50
1958  381.000000  64.530472  339.25   360.5  411.75
1959  428.333333  69.830097  387.50   406.5  465.25
1960  476.166667  77.737125  418.50   461.0  514.75

**Zadanie 8**
Pod koniec semestru studenci piszą test zalieczeniowy z którego można uzyskać $100$ punktów. Podzielmy możliwe do uzyskania wyniki punktowe z testu na $10$ grup z godnie ze słownikiem:
```python
grupy = {
    1: (0, 10),   
    2: (11, 20),
    3: (21, 30),   
    4: (31, 40),  
    5: (41, 50),  
    6: (51, 60),   
    7: (61, 70),   
    8: (71, 80),  
    9: (81, 90),   
    10: (91, 100)  
}
```
Z wieloletnich obserwacji wynika, że prawdopodobieństwa uzyskania wyniku z danej grupy punktowej są następujące:
```python
prawdopodobienstwa = [0.02, 0.03, 0.05, 0.1, 0.13, 0.16, 0.22, 0.18, 0.08, 0.03]
```
dla kolejnych grup punktowych.

Na podstawie otrzymanych danych zbuduj przykładdowe dane (ramkę danych) wyników z testu zaliczeniowego dla $200$ studentów (ustal ziarno generatora pseudolosowego).

Następnie, zgodnie ze skalą akadmicką wykorzystując fukcję `cut()` punkty - zmienną ilościową na zmieną kategoryczną:
* grupy 1-5 - ndst,
* grupa 6 - dst,
* grupa 7 - dst+,
* grupa 8 - db,
* grupa 9 - db+,
* grupa 10 - bdb.

In [ ]:
import numpy as np


groups = {
    1: (0, 10),
    2: (11, 20),
    3: (21, 30),
    4: (31, 40),
    5: (41, 50),
    6: (51, 60),
    7: (61, 70),
    8: (71, 80),
    9: (81, 90),
    10: (91, 100)
}

probabilities = [0.02, 0.03, 0.05, 0.1, 0.13, 0.16, 0.22, 0.18, 0.08, 0.03]

results = np.random.choice(
    list(groups.keys()),
    size=200,
    p=probabilities
)

points = []
for group in results:
    points.append(np.random.randint(groups[group][0], groups[group][1] + 1))

df = pd.DataFrame({'Student': range(1, 201), 'Points': points})

bins = [-1, 51, 61, 71, 81, 91, 101]
labels = ['ndst', 'dst', 'dst+', 'db', 'db+', 'bdb']

df['Grades'] = pd.cut(df['Points'], bins=bins, labels=labels)

print(df)

     Student  Points Grades
0          1      43   ndst
1          2      56    dst
2          3      53    dst
3          4      55    dst
4          5      65   dst+
..       ...     ...    ...
195      196      62   dst+
196      197      67   dst+
197      198      31   ndst
198      199      48   ndst
199      200      64   dst+

[200 rows x 3 columns]

**Zadanie 9**

W plikach *szczepionki.csv*  oraz *wizyty.csv* znajdują się dane dotyczące szczepień od 2 stycznia 2023 do 7 maja 2024. Pierwszy wiersz w każdym pliku jest wierszem nagłówkowym i zawiera nazwy odpowiednich pól. Dane w wierszach rozdzielone są znakiem
średnika.

Plik o nazwie *szczepionki.csv* zawiera informacje o szczepionkach. W każdym wierszu
znajduje się:
* `kod_szczepionki` – tekst do $10$ znaków, określający jednoznacznie szczepionkę;
* `liczba_dawek` – liczba rekomendowanych dawek, liczba całkowita większa od $0$ i mniejsza od $10$.

Plik o nazwie *wizyty.csv* zawiera informacje o podanej pacjentowi dawce szczepionki.
W każdym wierszu znajduje się:
* `pesel` – numer PESEL pacjenta przyjmującego daną dawkę szczepienia, składający się z $11$ znaków;
* `kod_szczepionki` – kod podanej szczepionki;
* `data_szczepienia` – data szczepienia w formacie `rrrr-mm-dd`;
* `numer_dawki` – liczba całkowita mniejsza od 10 określająca, która dawka szczepionki została podana.

Na podsatwie podanych plików utwórzy dwie ramki danych i odpwiedz na pytania:
1. Wypisz te szepionki dla których rekomednowana liczba dawek jest większa niż 5. Podaj ile dodoknano czepień w lipcu i sierpniu 2023 roku.
2. Dla każdej szczepionki podaj, ile łącznie jej dawek zostało podanych pacjentom. Jako wynik
podaj listę zawierającą kod szczepionki i liczbę dawek. Lista powinna być posortowana
nierosnąco według liczby dawek.
3. Podaj, ilu różnych pacjentów przyjęło przynajmniej jedną dawkę szczepionki o kodzie
sz12_3d`. Podaj, ile wśród nich było kobiet (płeć określa przedostatnia cyfra numeru PESEL,

In [ ]:
import pandas as pd
szczepionki_df = pd.read_csv('/content/drive/MyDrive/Analiza_Danych/szczepionki.csv', delimiter=';')
wizyty_df = pd.read_csv('/content/drive/MyDrive/Analiza_Danych/wizyty.csv', delimiter=';')

print("----Podpunkt 1----")

szczepionki_wieksze_niz_5 = szczepionki_df[szczepionki_df['liczba_dawek'] > 5]
if szczepionki_wieksze_niz_5.empty:
    print("Nie ma szczepionek, które mają rekomendowane więcej niż 5 dawek.")
else:
    print(f"Szczepionki, dla których rekomendowana liczba dawek jest większa niż 5:\n{szczepionki_wieksze_niz_5.to_string(index=False)}")

wizyty_df['data_szczepienia'] = pd.to_datetime(wizyty_df['data_szczepienia'])
szczepienia_lipiec_sierpien_2023 = wizyty_df[(wizyty_df['data_szczepienia'].dt.year == 2023) & (wizyty_df['data_szczepienia'].dt.month.isin([7, 8]))]
liczba_szczepien_lipiec_sierpien_2023 = szczepienia_lipiec_sierpien_2023.shape[0]
print(f"Liczba szczepień w lipcu i sierpniu 2023 roku: {liczba_szczepien_lipiec_sierpien_2023}")

print("----Podpunkt 2----")

dawki_per_szczepionka = wizyty_df.groupby('kod_szczepionki').size().reset_index(name='liczba_dawk')

dawki_per_szczepionka_sorted = dawki_per_szczepionka.sort_values(by='liczba_dawk', ascending=False)

print(dawki_per_szczepionka_sorted.to_string(index=False))

print("----Podpunkt 3----")

pacjenci_sz12_3d = wizyty_df[wizyty_df['kod_szczepionki'] == 'sz12_3d']

unikalni_pacjenci_sz12_3d = pacjenci_sz12_3d['pesel'].unique()
liczba_pacjentow_sz12_3d = len(unikalni_pacjenci_sz12_3d)

kobiety_sz12_3d = [pesel for pesel in unikalni_pacjenci_sz12_3d if int(str(pesel)[-2]) % 2 == 0]
liczba_kobiet_sz12_3d = len(kobiety_sz12_3d)

print(f"Liczba różnych pacjentów, którzy przyjęli przynajmniej jedną dawkę szczepionki sz12_3d: {liczba_pacjentow_sz12_3d}")
print(f"Liczba kobiet wśród tych pacjentów: {liczba_kobiet_sz12_3d}")

----Podpunkt 1----
Nie ma szczepionek, które mają rekomendowane więcej niż 5 dawek.
Liczba szczepień w lipcu i sierpniu 2023 roku: 62
----Podpunkt 2----
kod_szczepionki  liczba_dawk
        sz15_5d          111
        sz10_4d           83
        sz21_5d           82
        sz17_4d           81
        sz20_5d           79
         sz9_5d           73
         sz3_5d           72
        sz13_5d           71
         sz1_3d           69
         sz6_3d           64
        sz12_3d           60
         sz7_5d           60
        sz24_3d           59
        sz22_3d           45
        sz18_2d           38
        sz19_2d           35
         sz4_2d           34
         sz8_2d           29
        sz16_1d           28
        sz11_1d           25
        sz23_1d           23
         sz5_1d           23
        sz14_1d           16
         sz2_1d           15
----Podpunkt 3----
Liczba różnych pacjentów, którzy przyjęli przynajmniej jedną dawkę szczepionki sz12_3d: 24
Liczba kobiet wśród tych pacjentów: 17

**Zadanie 10**
Stwórz ramkę danych ```DataFrame```, która będzie zawierać 25 rekordów, gdzie każda kolumna będzie odpowiadać następującym atrybutowi (imię, wiek, miasto). Wykorzystaj poniższe dane do stworzenia rekordów, dane mogą się powtarzać.

```python
imie = ["Ala", "Tomek", "Ewa", "Olaf", "Michał", "Patryk", "Robert", "Natalia", "Zuzanna"]
wiek = np.random.randint(15,60, 10)
miasto = ["Warszawa", "Kraków", "Poznań", "Radom", "Toruń", "Kielce", "Sopot", "Olsztyn"]
```

Wykonaj następujące zadania:

1. zamień nazwy kolumn na angielskie odpowiedniki
2. dodaj nową kolumnę "Occupation" (zawód) i przypisz każdemu dowolny zawód (minimum 5 zawodów dla wszystkich rekordów, dane mogą się powtarzać)
3. posortuj ```DataFrame``` po wieku w porządku rosnącym
4. pogrupuj dane po zawodach (occupation) i zwróć ich liczbę

In [ ]:
imie = ["Ala", "Tomek", "Ewa", "Olaf", "Michał", "Patryk", "Robert", "Natalia", "Zuzanna"]
wiek = np.random.randint(15, 60, 25)
miasto = ["Warszawa", "Kraków", "Poznań", "Radom", "Toruń", "Kielce", "Sopot", "Olsztyn"]


df = pd.DataFrame({
    'imie': np.random.choice(imie, 25),
    'wiek': wiek,
    'miasto': np.random.choice(miasto, 25)
})

# 1:
df.columns = ['Name', 'Age', 'City']

# 2:
occupations = ["Engineer", "Doctor", "Teacher", "Artist", "Lawyer"]
df['Occupation'] = np.random.choice(occupations, 25)

# 3:
df_sorted = df.sort_values(by='Age')

# 4:
occupation_group = df.groupby('Occupation').size()


print("Sorted DataFrame by Age:")
print(df_sorted)

print("\nCount of Occupations:")
print(occupation_group)

Sorted DataFrame by Age:
       Name  Age      City Occupation
9    Robert   15    Poznań     Lawyer
10   Michał   18   Olsztyn     Lawyer
2      Olaf   19  Warszawa    Teacher
18      Ala   19    Kraków   Engineer
8       Ewa   19   Olsztyn    Teacher
12    Tomek   21     Sopot     Lawyer
17  Zuzanna   21  Warszawa     Artist
3       Ala   22     Sopot     Doctor
1   Natalia   28   Olsztyn     Doctor
24      Ewa   30     Sopot     Doctor
4   Zuzanna   31    Kraków     Doctor
13  Natalia   34    Kraków    Teacher
22   Patryk   36    Kielce     Lawyer
0   Natalia   37    Kraków     Doctor
15     Olaf   39    Kraków     Artist
20      Ewa   39     Radom     Artist
11    Tomek   41    Kielce     Lawyer
23  Zuzanna   42     Radom     Artist
19    Tomek   49  Warszawa     Doctor
6   Zuzanna   52    Kielce    Teacher
7       Ewa   52   Olsztyn    Teacher
16      Ewa   53    Poznań   Engineer
5   Natalia   54     Radom     Lawyer
14     Olaf   56     Sopot     Lawyer
21   Michał   58     Toruń    Teacher

Count of Occupations:
Occupation
Artist      4
Doctor      6
Engineer    2
Lawyer      7
Teacher     6
dtype: int64

**Zadanie 11**
Plik *products.csv* zawiera dane o sprzedaży produktów, dane podzielone są na kolumny o nazwach `produkt_id`, `product_name`, `price`, `quantity`. Załaduj dane do do ```DataFeame``` i wykonaj następujące zadania:

1. Stwórz nową kolumnę o nazwie `total_sales`, która będzie iloczynem ceny i liczby sprzedanych produktów
2. Posortuje produkty według wartości sprzedanych produktów (`total_sales`) według porządku rosnącego, następnie wsakrz 3 produkty o najniższej sumie sprzedaży i trzy produkty o najwyżej sumie sprzedaży
3. Oblicz średnią cenę produktu a następnie wyszukaj produkty, które mieszczą się w przedziale `średnia cena - 50` a `średnia cena + 50`. Porównaj wyszukane produkty z produktem o najwyższej sumie sprzedaży
4. Wyszukaj 5 produktów o najniższej cenie i zasymuluj jak by wyglądały wyniki sprzedaży jeżeli produkty byłyby sprzedawane po wyższej cenie. Wykonaj symulację dla cen pomnożonych przez `1.2`, `1.5`, `1.7` wyniki zapisz w osobnych plikach *.csv*

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Analiza_Danych/products.csv')


df['total_sales'] = df['price'] * df['quantity']

sorted_df = df.sort_values(by='total_sales')
lowest_sales = sorted_df.head(3)
highest_sales = sorted_df.tail(3)

print("Three products with the lowest total sales:")
print(lowest_sales[['product_name', 'total_sales']])

print("\nThree products with the highest total sales:")
print(highest_sales[['product_name', 'total_sales']])


average_price = df['price'].mean()
price_range = df[(df['price'] >= average_price - 50) & (df['price'] <= average_price + 50)]

highest_sales_product = sorted_df.tail(1)

print("\nProducts within the price range of average price ± 50:")
print(price_range[['product_name', 'price']])

print("\nProduct with the highest total sales:")
print(highest_sales_product[['product_name', 'total_sales']])


lowest_price_products = df.nsmallest(5, 'price')
simulated_sales_1_2 = lowest_price_products.copy()
simulated_sales_1_5 = lowest_price_products.copy()
simulated_sales_1_7 = lowest_price_products.copy()


simulated_sales_1_2['price'] *= 1.2
simulated_sales_1_2['total_sales'] = simulated_sales_1_2['price'] * simulated_sales_1_2['quantity']

simulated_sales_1_5['price'] *= 1.5
simulated_sales_1_5['total_sales'] = simulated_sales_1_5['price'] * simulated_sales_1_5['quantity']

simulated_sales_1_7['price'] *= 1.7
simulated_sales_1_7['total_sales'] = simulated_sales_1_7['price'] * simulated_sales_1_7['quantity']

simulated_sales_1_2.to_csv('simulated_sales_1_2.csv', index=False)
simulated_sales_1_5.to_csv('simulated_sales_1_5.csv', index=False)
simulated_sales_1_7.to_csv('simulated_sales_1_7.csv', index=False)

Three products with the lowest total sales:
        product_name  total_sales
16  Smart Light Bulb       145.60
24           Charger       999.50
12          Smart TV      1002.24

Three products with the highest total sales:
       product_name  total_sales
9        Smartwatch     61622.19
10           Laptop     75388.95
4   Washing Machine     79668.32

Products within the price range of average price ± 50:
    product_name   price
28          Lens  299.99
31     Projector  350.00
33  Game Console  299.99
39  Robot Vacuum  299.99

Product with the highest total sales:
      product_name  total_sales
4  Washing Machine     79668.32